// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJZTbW5eJgEKklht1SC6jvMoGB1_I2rUQ',
    appId: '1:27525477486:web:14f393cf5cfa560912627f',
    messagingSenderId: '27525477486',
    projectId: 'orderly-app-c56e3',
    authDomain: 'orderly-app-c56e3.firebaseapp.com',
    storageBucket: 'orderly-app-c56e3.firebasestorage.app',
    measurementId: 'G-LH5JS1R099',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzGloDPJRCiYfEulkbdrVyp2JWMkTlnaA',
    appId: '1:27525477486:android:78f4d57fef463c8412627f',
    messagingSenderId: '27525477486',
    projectId: 'orderly-app-c56e3',
    storageBucket: 'orderly-app-c56e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8UQwtIxT8EdjJhxBsr5yRxg6hGXyjXW8',
    appId: '1:27525477486:ios:a93ca7dce5584dbd12627f',
    messagingSenderId: '27525477486',
    projectId: 'orderly-app-c56e3',
    storageBucket: 'orderly-app-c56e3.firebasestorage.app',
    iosBundleId: 'com.example.orderlyAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8UQwtIxT8EdjJhxBsr5yRxg6hGXyjXW8',
    appId: '1:27525477486:ios:a93ca7dce5584dbd12627f',
    messagingSenderId: '27525477486',
    projectId: 'orderly-app-c56e3',
    storageBucket: 'orderly-app-c56e3.firebasestorage.app',
    iosBundleId: 'com.example.orderlyAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJZTbW5eJgEKklht1SC6jvMoGB1_I2rUQ',
    appId: '1:27525477486:web:8dfddaf238ab1f6f12627f',
    messagingSenderId: '27525477486',
    projectId: 'orderly-app-c56e3',
    authDomain: 'orderly-app-c56e3.firebaseapp.com',
    storageBucket: 'orderly-app-c56e3.firebasestorage.app',
    measurementId: 'G-2BRT8MFVXG',
  );
}
